### PR TITLE
add initial styling to index.erb

### PR DESCRIPTION
**Pull request by Ecksi**
Any of you happen to know how I would link to a css stylesheet? 

I had tried <%= stylesheet_link_tag "main" %> inside my head tag
I had a main.css file in multiple locations, but kept getting errors. Not sure what I'm missing.

But if ya guys don't have a problem with this styling can you merge to master please.

### CODE REVIEW

**Comment by seoulstice** [comment]
I think you would create this directory and add it in there " app/assets/stylesheets/"

And in the head of the erb file : 
<link rel="stylesheet" href="/stylesheets/master.css"> although you might want to play around with that href because that's probably not right

**Comment by seoulstice** [comment]
<<link rel="stylesheet" href="/css/master.css > but fix that i had to write it incorrectly for it to be visiible on github

**Comment by Maxscores** [comment]
It's the same way as if you had it in the head of an HTML document. Not sure if you neeed to create a head tag to put it in, but use the link href stuff

**Comment by Maxscores** [comment]
I'm going to close this request and move it all into a stylesheet. Will submit another PR when that's done.

**Comment by icorson3** [comment]
`style_tag_link` is a rails method so you should use `<link` and reference the file in the `<head>` of the document

**Review by icorson3 — COMMENTED** [review]
style_tag_link is a rails method so you should use <link and reference the file in the <head> of the document

**Pull request closed without merging**
